# llm_service.py
import google.generativeai as genai
from dotenv import load_dotenv
import os

# Load environment variables
load_dotenv()
genai.configure(api_key=os.getenv("GEMINI_API_KEY"))

# Initialize the Gemini model
model = genai.GenerativeModel("models/gemini-flash-latest")

def generate_advice(context):
    """
    Generate farmer-friendly advisory based on crop disease, location, weather, and pesticide info.

    Parameters:
        context (dict): Dictionary containing disease, location, weather, pesticide dosage, and safety info.

    Returns:
        str: Advisory text generated by the model.
    """

    # Ensure the correct key is used for dosage
    dosage_info = context.get("dosage_per_liter", "Dosage info not available")

    prompt = f"""
You are an agricultural advisory assistant.

Disease: {context.get('disease', 'Unknown')}
Location: {context.get('location', 'Unknown')}
Temperature: {context.get('temperature', 'N/A')} °C
Humidity: {context.get('humidity', 'N/A')} %
Rainfall: {context.get('rainfall', 'N/A')}

Chemical pesticide: {context.get('chemical', 'Unknown')}
Dosage: {dosage_info}

Organic remedies: {', '.join(context.get('organic', []))}
Safety rules: {', '.join(context.get('safety', []))}

Explain clearly in simple language for farmers.
"""

    # Generate the content
    response = model.generate_content(prompt)

    # Return the generated text
    return response.text
